### PR TITLE
Used symbolic icons

### LINKED ISSUE #12: Use symbolic icons
I think it would look better, and more native on pinephone

### PR DESCRIPTION
**Pull request by Schmiddiii**
All the icons should now be symblic.
The watch-later button icon has been changed from `appointment-soon` to `appointment-new` as I did not like
`appointment-soon-symbolic`.
The images in the README still need to be updated.

Closes #12

### CODE REVIEW

**Comment by SeaDve** [comment]
It definitely looks better, although for some reason, the icons are bigger than normal.

I built it and it looks like this:
I might've build it wrong

image

**Comment by Schmiddiii** [comment]
I did not change the icon size. It was always LargeToolbar.
I tested SmallToolbar and Button but on the Pinephone I think LargeToolbar looks best.
Maybe a third opinion would be helpful. 

I have prepared a small diff you can apply to test out the different sizes.
The `filter`-Page will have a SmallToolbar add-button,
the `subscriptions`-Page will have LargeToolbar add-button.

[tubefeeder_diff.txt](https://github.com/Schmiddiii/Tubefeeder/files/6609546/tubefeeder_diff.txt)

**Comment by SeaDve** [comment]
You could also put icons on the view switcher below like this:
image

I would like to work on it, but my knowledge of rust is not very well

**Comment by Schmiddiii** [comment]
I already wanted to do that long ago, but I did not find matching icons.
Could you recommend any icons.
Please note that these icons should already be preinstalled, I do not want to create icons myself.

**Comment by SeaDve** [comment]
I'll try

**Comment by Schmiddiii** [comment]
I think this looks pretty nice.
The implementation is probably a little bit hacky as I have no idea what I was doing, but it seems to work.

The screenshots will have to be updated again.
I will wait for these screenshots until you confirmed that everything is ok.
Any suggestions for UI updates are still welcome.

**Pull request merged**
